JUDGE0_VERSION=1.13.1

# ------------------------------------------------------------------------------
# REDIS CONFIGURATION
# ------------------------------------------------------------------------------
REDIS_PASSWORD=judge0redispassword
REDIS_HOST=redis
REDIS_PORT=6379

# ------------------------------------------------------------------------------
# POSTGRESQL CONFIGURATION
# ------------------------------------------------------------------------------
POSTGRES_USER=judge0
POSTGRES_PASSWORD=password
POSTGRES_DB=judge0
POSTGRES_HOST=db
POSTGRES_PORT=5432
