from typing import List, TYPE_CHECKING
from sqlalchemy import ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.database import Base

if TYPE_CHECKING:
    from app.models.journey import Journey
    from app.models.task import Task

class DailyPlan(Base):
    __tablename__ = "daily_plans"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    journey_id: Mapped[int] = mapped_column(ForeignKey("journeys.id"))
    day_number: Mapped[int]
    topics: Mapped[str] # Specific topics assigned by the Planner for this day
    theoretical_topic_content: Mapped[str] # The theory/content generated by the Content Creator AI
    completion_status: Mapped[bool] = mapped_column(default=False)

    # Relationships
    journey: Mapped["Journey"] = relationship(back_populates="daily_plans")
    tasks: Mapped[List["Task"]] = relationship(back_populates="daily_plan", cascade="all, delete-orphan")
