apiVersion: v1
data:
  judge0.conf: |
    JUDGE0_VERSION=1.13.1

    # ------------------------------------------------------------------------------
    # REDIS CONFIGURATION
    # ------------------------------------------------------------------------------
    REDIS_PASSWORD=judge0redispassword
    REDIS_HOST=judge0-redis
    REDIS_PORT=6379

    # ------------------------------------------------------------------------------
    # POSTGRESQL CONFIGURATION
    # ------------------------------------------------------------------------------
    POSTGRES_USER=judge0
    POSTGRES_PASSWORD=password
    POSTGRES_DB=judge0
    POSTGRES_HOST=judge0-db
    POSTGRES_PORT=5432
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: server
  name: server-cm0
