apiVersion: v1
data:
  JUDGE0_VERSION: 1.13.1
  POSTGRES_DB: judge0
  POSTGRES_HOST: judge0-db
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: "5432"
  POSTGRES_USER: judge0
  REDIS_HOST: judge0-redis
  REDIS_PASSWORD: judge0redispassword
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: judge0-db-judge0-conf
  name: judge0-conf
