"""sync_journey_columns

Revision ID: 3939786b58e8
Revises: 20e8fd31780b
Create Date: 2026-05-04 15:10:48.096372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3939786b58e8'
down_revision: Union[str, Sequence[str], None] = '20e8fd31780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column('daily_plans', sa.Column('concepts_to_cover', sa.JSON(), nullable=False))
    # op.add_column('daily_plans', sa.Column('difficulty', sa.String(), nullable=False))
    # op.drop_column('daily_plans', 'theoretical_topic_content')
    # op.drop_column('daily_plans', 'completion_status')
    # op.add_column('journeys', sa.Column('original_prompt', sa.String(), nullable=False))
    # op.add_column('journeys', sa.Column('target_days', sa.Integer(), nullable=False))
    # op.add_column('journeys', sa.Column('journey_title', sa.String(), nullable=True))
    # op.add_column('journeys', sa.Column('overview', sa.String(), nullable=True))
    # op.add_column('journeys', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # op.drop_column('journeys', 'total_days')
    # op.drop_column('journeys', 'title')
    # op.drop_column('journeys', 'initial_user_prompt')
    # op.drop_column('journeys', 'objectives')
    # op.drop_column('journeys', 'start_date')
    # op.drop_column('journeys', 'status')
    # op.add_column('tasks', sa.Column('problem_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_column('tasks', 'problem_id')
    # op.add_column('journeys', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('journeys', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # op.add_column('journeys', sa.Column('objectives', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('journeys', sa.Column('initial_user_prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('journeys', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('journeys', sa.Column('total_days', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.drop_column('journeys', 'created_at')
    # op.drop_column('journeys', 'overview')
    # op.drop_column('journeys', 'journey_title')
    # op.drop_column('journeys', 'target_days')
    # op.drop_column('journeys', 'original_prompt')
    # op.add_column('daily_plans', sa.Column('completion_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # op.add_column('daily_plans', sa.Column('theoretical_topic_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('daily_plans', 'difficulty')
    # op.drop_column('daily_plans', 'concepts_to_cover')
    # # op.drop_column('daily_plans', 'title')
    # ### end Alembic commands ###
