"""Restore user_id to knowledge_sources

Revision ID: 43bc6f69bb2c
Revises: 3939786b58e8
Create Date: 2026-05-05 20:16:10.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bc6f69bb2c'
down_revision = '3939786b58e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column('knowledge_sources', sa.Column('user_id', sa.Integer(), nullable=True))
    # op.create_index(op.f('ix_knowledge_sources_user_id'), 'knowledge_sources', ['user_id'], unique=False)
    # op.create_foreign_key('fk_knowledge_sources_user_id_users', 'knowledge_sources', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_constraint('fk_knowledge_sources_user_id_users', 'knowledge_sources', type_='foreignkey')
    # op.drop_index(op.f('ix_knowledge_sources_user_id'), table_name='knowledge_sources')
    # op.drop_column('knowledge_sources', 'user_id')
    # ### end Alembic commands ###
