"""add journey_id to chat_messages

Revision ID: 4c82059219ca
Revises: 91bbb10bada4
Create Date: 2026-06-09 13:58:35.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c82059219ca'
down_revision: Union[str, Sequence[str], None] = '91bbb10bada4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('journey_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_chat_messages_journey_id_journeys', 'chat_messages', 'journeys', ['journey_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_messages_journey_id_journeys', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'journey_id')
    # ### end Alembic commands ###
