"""Add prompt_embedding to journeys

Revision ID: 82109baffc07
Revises: f23f7e0760e0
Create Date: 2026-06-13 13:45:01.679360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82109baffc07'
down_revision: Union[str, Sequence[str], None] = 'f23f7e0760e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journeys', sa.Column('prompt_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journeys', 'prompt_embedding')
    # ### end Alembic commands ###
