"""Add content status and tags to daily plan

Revision ID: 91bbb10bada4
Revises: 91e80f11157f
Create Date: 2026-05-24 18:02:05.164263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bbb10bada4'
down_revision: Union[str, Sequence[str], None] = '91e80f11157f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plans', sa.Column('content_status', sa.String(), nullable=False))
    op.add_column('daily_plans', sa.Column('recommended_problem_tags', sa.JSON(), nullable=True))
    op.add_column('daily_plans', sa.Column('theoretical_topic_content', sa.String(), nullable=True))
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plans', 'theoretical_topic_content')
    op.drop_column('daily_plans', 'recommended_problem_tags')
    op.drop_column('daily_plans', 'content_status')
    # ### end Alembic commands ###
