"""Add independent CodingProblem model

Revision ID: 91e80f11157f
Revises: 43bc6f69bb2c
Create Date: 2026-05-24 15:17:25.354260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e80f11157f'
down_revision: Union[str, Sequence[str], None] = '43bc6f69bb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('coding_problems',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('problem_id', sa.String(), nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.Column('description', sa.String(), nullable=False),
    # sa.Column('difficulty', sa.String(), nullable=False),
    # sa.Column('tags', sa.JSON(), nullable=False),
    # sa.Column('starter_code', sa.String(), nullable=False),
    # sa.Column('hidden_solution', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_coding_problems_id'), 'coding_problems', ['id'], unique=False)
    # op.create_index(op.f('ix_coding_problems_problem_id'), 'coding_problems', ['problem_id'], unique=True)
    # # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_coding_problems_problem_id'), table_name='coding_problems')
    # op.drop_index(op.f('ix_coding_problems_id'), table_name='coding_problems')
    # op.drop_table('coding_problems')
    # # ### end Alembic commands ###
    pass