"""add_socratic_context

Revision ID: f23f7e0760e0
Revises: 91e80f11157f
Create Date: 2026-06-09 14:04:28.839001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f23f7e0760e0'
down_revision: Union[str, Sequence[str], None] = '4c82059219ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plans', sa.Column('rag_context_payload', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_plans', 'rag_context_payload')
    # ### end Alembic commands ###
